package com.shadowascent.client.rendering;

import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.math.Matrix4;
import com.shadowascent.core.physics.TileRect;
import com.shadowascent.core.simulation.GameSimulator;
import com.shadowascent.core.simulation.SimEnemy;
import com.shadowascent.core.simulation.SimNPC;
import com.shadowascent.core.simulation.SimPlayer;

import java.util.List;

/**
 * P3 sprite renderer — draws simulation entities and tile geometry using a
 * TextureAtlas loaded by AssetManager. Replaces StubWorldRenderer.
 *
 * Placeholder regions are solid-color rectangles generated by SpritePackerTool.
 * Real art drops in by updating assets/sprites/raw/ and re-running packSprites —
 * no code changes required.
 *
 * Note: UV orientation matches LibGDX Y-up convention. With setToOrtho(true),
 * solid-color placeholders are unaffected; authored sprites should be packed
 * right-side up and will render correctly via the projection matrix.
 */
public final class SpriteWorldRenderer {

    private static final String REGION_PLAYER_IDLE     = "player_idle";
    private static final String REGION_PLAYER_DEAD     = "player_dead";
    private static final String REGION_ENEMY_WALK      = "enemy_walk";
    private static final String REGION_NPC_IDLE        = "npc_idle";
    private static final String REGION_TILE_GROUND     = "tile_ground";
    private static final String REGION_TILE_PLATFORM   = "tile_platform";

    private final SpriteBatch    batch;
    private final TextureAtlas   atlas;

    public SpriteWorldRenderer(SpriteBatch batch, TextureAtlas atlas) {
        this.batch = batch;
        this.atlas = atlas;
    }

    public void render(GameSimulator simulator, List<TileRect> tiles, Matrix4 projMatrix) {
        batch.setProjectionMatrix(projMatrix);
        batch.begin();

        for (TileRect tile : tiles) {
            TextureRegion r = region(tile.isPlatform() ? REGION_TILE_PLATFORM : REGION_TILE_GROUND);
            batch.draw(r, tile.x(), tile.y(), tile.w(), tile.h());
        }

        for (SimPlayer p : simulator.getPlayers()) {
            TextureRegion r = region(p.isDead ? REGION_PLAYER_DEAD : REGION_PLAYER_IDLE);
            batch.draw(r, p.physics.x, p.physics.y, p.physics.width, p.physics.height);
        }

        for (SimEnemy e : simulator.getEnemies()) {
            if (!e.isAlive()) continue;
            batch.draw(region(REGION_ENEMY_WALK), e.physics.x, e.physics.y,
                       e.physics.width, e.physics.height);
        }

        for (SimNPC npc : simulator.getNpcs()) {
            batch.draw(region(REGION_NPC_IDLE), npc.physics.x, npc.physics.y,
                       npc.physics.width, npc.physics.height);
        }

        batch.end();
    }

    private TextureRegion region(String name) {
        TextureRegion r = atlas.findRegion(name);
        return r != null ? r : atlas.findRegion(REGION_TILE_GROUND);
    }
}
